# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.cache/wt [current_project]
set_property parent.project_path C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Adder_3_Bit.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Decoder_2_to_4.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Decoder_3_to_8.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Instruction_decoder.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/LUT_16_7.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/new/MUX_8_way_4_bit.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Mux_2_to_4.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/NanoProcessor.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/ProgramCounter.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Program_ROM.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/RCA_4.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/RegisterBank.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/Slow_Clk.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/reg.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/twoWay_3Bit_Mux.vhd
  C:/Uni/Vivado/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.srcs/sources_1/imports/temp/MasterNanoProcessor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MasterNanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MasterNanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MasterNanoProcessor_utilization_synth.rpt -pb MasterNanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
