webtalk_init -webtalk_dir D:/uni/Semester_2/4-CS1050ComputerOrganizationAndDigitalDesign-3/labs/Lab9_4bitRegsWorking-20220730T104443Z-001/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.sim/sim_1/behav/xsim/xsim.dir/TB_Master_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 30 16:26:44 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9d6ae7abd82352188e71e930b3a38f07" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "96ff3bbc60274814936cb39d815bce93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6860_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3172214770 -regid "" -xml D:/uni/Semester_2/4-CS1050ComputerOrganizationAndDigitalDesign-3/labs/Lab9_4bitRegsWorking-20220730T104443Z-001/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.sim/sim_1/behav/xsim/xsim.dir/TB_Master_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/uni/Semester_2/4-CS1050ComputerOrganizationAndDigitalDesign-3/labs/Lab9_4bitRegsWorking-20220730T104443Z-001/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.sim/sim_1/behav/xsim/xsim.dir/TB_Master_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/uni/Semester_2/4-CS1050ComputerOrganizationAndDigitalDesign-3/labs/Lab9_4bitRegsWorking-20220730T104443Z-001/Lab9_4bitRegsWorking/Lab9_4bitRegsWorking.sim/sim_1/behav/xsim/xsim.dir/TB_Master_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
