@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jul 30 16:20:28 +0530 2022
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim TB_Master_behav -key {Behavioral:sim_1:Functional:TB_Master} -tclbatch TB_Master.tcl -view D:/uni/Semester_2/4-CS1050ComputerOrganizationAndDigitalDesign-3/labs/Lab9_4bitRegsWorking-20220730T104443Z-001/Lab9_4bitRegsWorking/TB_Master_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
